# Повідомлення які будуть використовуватись для повідомлень про вхід/вихід гравців
# Досутупні плейсхолдери {p} - гравець, {t} - час, {d} - дата, {l} - локація, {w} - вимір
messages:
  # Вимкнути стандартне повідомлення
  disable-default-server-messages: true
  # Звичайні повідомлення
  default:
    join:
      - "{p} join the game"
    leave:
      - "{p} quit the game"
  # Повідомлення на базі прав
  permission:
    prime:
      join:
        - "prime user {p} join the game"
      leave:
        - "prime user {p} quit the game"
    admin:
      join:
        - "admin {p} join the game"
      leave:
        - "admin {p} quit the game"
  # Повідомлення на базі псевдонімів
  nickname:
    example:
      join:
        - "Hi {p} join the game"
      leave:
        - "Bye {p} quit the game"
  # Системні повідомлення
  system:
    enable: "Lejo plugin enabled"
    disable: "Lejo plugin disabled"
    reload: "Lejo plugin reload"
    info: "§a Lejo is a lightweight and flexible plugin for Minecraft (Paper/Purpur) that allows full customization of join and quit messages. It supports gradients, Hex colors, formatting with placeholders, and logic based on permissions, world, nickname, and more"
  placeholders:
    time-format: "HH:mm:ss"
    date-format: "dd.MM.yyyy"
    location-format: "x:{x} y:{y} z:{z}"
    worlds:
      nether: "nether"
      overworld: "overworld"
      end: "end"
      custom: "custom"
# Значок який буде викорисовувати плагін
prefix:
  # Якщо ви хочете, щоб значок був після повідомлення, зазвичай false
  suffix-mode: false
  join: [+]
  leave: [-]
